delete from EVENEMENT_PARTICIPANTS
delete from EVENEMENT
delete from COURRIER_ETAPES
delete from PRESENCE
delete from INVITATION
delete from COURRIER
delete from ETAPE
delete from INVITE
delete from FOYER
delete from AUTORISATION
delete from UTILISATEUR
delete from MARIAGE
