delete from COURRIER_ETAPES
delete from INVITE_ETAPE_PRESENCE
delete from FOYER_COURRIER_INVITATION
delete from COURRIER
delete from ETAPE
delete from INVITE
delete from FOYER
delete from AUTORISATION
delete from UTILISATEUR
delete from MARIAGE
