create table evenement (id bigint generated by default as identity (start with 1), debut timestamp, fin timestamp, titre varchar(255), mariage_id bigint, primary key (id));
create table evenement_participants (evenement bigint not null, participants varchar(255) not null);
alter table evenement_participants add constraint UK_6h7gw3r3tkq5co0qxoj721bxn unique (participants);
alter table evenement add constraint FK_s4r3hice8371sei9plvbjy44x foreign key (mariage_id) references mariage;
alter table evenement_participants add constraint FK_6h7gw3r3tkq5co0qxoj721bxn foreign key (participants) references utilisateur;
alter table evenement_participants add constraint FK_7h0wdhxcciabn4ire4c9ng8jy foreign key (evenement) references evenement;
